import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="  bg-black">
        <header className="">
          <NavBar />
        </header>
        <main className="text-wlite z-10 ">{children}</main>
        <footer className="relative z-50">
          <Footer />
        </footer>
      </body>
    </html>
  );
}
